export const OPEN_TIP_OPERATE_BOX = 'OPEN_TIP_OPERATE_BOX'
export const CLOSE_TIP_OPERATE_BOX = 'CLOSE_TIP_OPERATE_BOX'
export const SURE_TIP_OPERATE_BOX = 'SURE_TIP_OPERATE_BOX'

export const OPEN_TOAST = 'OPEN_TOAST'
export const CLOSE_TOAST = 'CLOSE_TOAST'
